server:
  port: 8090

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: "true"
    change-log: db/changelog/db.changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: as4n.tsu@gmail.com
    password: gsvo mrrd yqfa gilg
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

jwt:
  secret: hits2025972303hits2025972303hits20259723032025hits
  lifetime: 600m

